## app
app.version=1.0.0
app.logging.level=INFO
app.env=TEST
app.organization=1
app.url=https://smagg.linktera.xyz

## async
async.corePoolSize=3
async.maxPoolSize=3
async.queueCapacity=100

## jackson
spring.jackson.time-zone=Europe/Istanbul
spring.jackson.locale=tr-TR

## jasypt
jasypt.encryptor.password=PASSWORD

## logging
logging.level.root=INFO
logging.level.com.zaxxer.hikari.HikariConfig=DEBUG
logging.file.name=/var/log/smartaggregator.log
logging.pattern.file=%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n
logging.pattern.console=%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n

## jpa
spring.jpa.properties.hibernate.jdbc.batch_size=100
spring.jpa.properties.hibernate.order_inserts=true
#spring.jpa.properties.hibernate.generate_statistics=true
#spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.use_sql_comments=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.default_schema=PUBLIC
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true

## db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:file:./smartaggregator-db;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.initialization-mode=always
spring.datasource.data=file:/Users/onurkardes/Antigravity/LAD/smartaggregator/config/data.sql
spring.datasource.continue-on-error=true
## hikari
spring.datasource.hikari.schema=PUBLIC
spring.datasource.hikari.minimumIdle=10
spring.datasource.hikari.maximumPoolSize=100
spring.datasource.hikari.idleTimeout=300000
spring.datasource.hikari.maxLifetime=2000000
spring.datasource.hikari.connectionTimeout=300000
spring.datasource.hikari.leakDetectionThreshold=300000

#Mail Sending Properties
spring.mail.host=smtp.office365.com
spring.mail.port=587
spring.mail.username=robot@linktera.com.tr
spring.mail.password=Poy06899
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.debug=true

## server
server.error.whitelabel.enabled=false
#server.max-http-header-size=48KB
server.port=8080

# LDAP
spring.ldap.urls=ldap://10.222.21.29:389
spring.ldap.base=dc=linktera,dc=com,dc=tr
app.ldap.commons=cn=users,cn=accounts
app.ldap.principalPrefix=uid
app.ldap.principalSuffix=
app.ldap.auth=simple
app.ldap.protocol=
spring.data.ldap.repositories.enabled=false

#Switch Authentication Method: ldap/default
app.auth.method=default

# liquibase
spring.liquibase.enabled=false
spring.liquibase.change-log=classpath:/db/changelog/changelog.xml
spring.liquibase.database-change-log-table=LIQ_DATABASE_CHANGELOG
spring.liquibase.database-change-log-lock-table=LIQ_DATABASE_CHANGELOG_LOCK
logging.level.liquibase=INFO