export LANG='en_US.UTF-8'
export JAVA_OPTS='-Dspring.profiles.active=h2 -Dspring.datasource.initialization-mode=never -Xmx8192m -Xms1024m -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/data/apps/smartaggregator/heapdump.bin'
